USE [EKP_WORKFLOW]
GO

/****** Object:  Table [dbo].[TB_TEST_API]    Script Date: 2020-02-06 ¿ÀÀü 10:48:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TEST_API](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[SUBJECT] [nvarchar](100) NULL,
	[CONTENT] [nvarchar](1000) NULL,
	[CREATE_DT] [datetime] NULL,
 CONSTRAINT [PK__TB_TEST_API] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


